[project]
name = "glitch-machine-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate==0.30.1",
    "compel==2.0.2",
    "controlnet-aux==0.0.9",
    "diffusers==0.28.2",
    "fastapi==0.111.0",
    "huggingface-hub==0.24.0",
    "lunar-tools",
    "markdown2>=2.5.3",
    "mpmath==1.3.0",
    "numpy==1.*",
    "onediff ; platform_machine != 'arm64' or sys_platform != 'darwin'",
    "oneflow ; platform_machine != 'arm64' or sys_platform != 'darwin'",
    "onnxruntime>=1.21.0",
    "optimum>=1.24.0",
    "peft==0.11.1",
    "pillow==10.3.0",
    "pyaudio>=0.2.14",
    "rembg>=2.0.64",
    "safetensors>=0.5.3",
    "setuptools>=76.0.0",
    "stable-fast>=1.0.5",
    "torch==2.2.2",
    "transformers==4.41.1",
    "uvicorn[standard]==0.30.0",
    "xformers>=0.0.25.post1 ; platform_machine != 'arm64' or sys_platform != 'darwin'",
]

[tool.uv.sources]
oneflow = { url = "https://github.com/siliconflow/oneflow_releases/releases/download/community_cu122/oneflow-0.9.1.dev20231222+cu122-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl" }
onediff = { git = "https://github.com/siliconflow/onediff.git", rev = "main" }
lunar-tools = { git = "https://github.com/lunarring/lunar_tools" }
