# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import generation_control_pb2 as generation__control__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in generation_control_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GenerationControlStub(object):
    """Generation control service for real-time diffusion parameters
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetPrompt = channel.unary_unary(
                '/generation_control.GenerationControl/SetPrompt',
                request_serializer=generation__control__pb2.PromptRequest.SerializeToString,
                response_deserializer=generation__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.SetGenerationParams = channel.unary_unary(
                '/generation_control.GenerationControl/SetGenerationParams',
                request_serializer=generation__control__pb2.GenerationParamsRequest.SerializeToString,
                response_deserializer=generation__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.SetControlNetParams = channel.unary_unary(
                '/generation_control.GenerationControl/SetControlNetParams',
                request_serializer=generation__control__pb2.ControlNetParamsRequest.SerializeToString,
                response_deserializer=generation__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.SetLoRAParams = channel.unary_unary(
                '/generation_control.GenerationControl/SetLoRAParams',
                request_serializer=generation__control__pb2.LoRAParamsRequest.SerializeToString,
                response_deserializer=generation__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.SetPromptTravelParams = channel.unary_unary(
                '/generation_control.GenerationControl/SetPromptTravelParams',
                request_serializer=generation__control__pb2.PromptTravelParamsRequest.SerializeToString,
                response_deserializer=generation__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.SetAcidParams = channel.unary_unary(
                '/generation_control.GenerationControl/SetAcidParams',
                request_serializer=generation__control__pb2.AcidParamsRequest.SerializeToString,
                response_deserializer=generation__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.SwitchCuration = channel.unary_unary(
                '/generation_control.GenerationControl/SwitchCuration',
                request_serializer=generation__control__pb2.SwitchCurationRequest.SerializeToString,
                response_deserializer=generation__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.GetCurrentState = channel.unary_unary(
                '/generation_control.GenerationControl/GetCurrentState',
                request_serializer=generation__control__pb2.GetStateRequest.SerializeToString,
                response_deserializer=generation__control__pb2.CurrentStateResponse.FromString,
                _registered_method=True)
        self.BatchUpdate = channel.unary_unary(
                '/generation_control.GenerationControl/BatchUpdate',
                request_serializer=generation__control__pb2.BatchUpdateRequest.SerializeToString,
                response_deserializer=generation__control__pb2.ControlResponse.FromString,
                _registered_method=True)
        self.StartPromptJourney = channel.unary_unary(
                '/generation_control.GenerationControl/StartPromptJourney',
                request_serializer=generation__control__pb2.PromptJourneyRequest.SerializeToString,
                response_deserializer=generation__control__pb2.PromptJourneyResponse.FromString,
                _registered_method=True)
        self.GetJourneyStatus = channel.unary_unary(
                '/generation_control.GenerationControl/GetJourneyStatus',
                request_serializer=generation__control__pb2.GetStateRequest.SerializeToString,
                response_deserializer=generation__control__pb2.PromptJourneyStatus.FromString,
                _registered_method=True)
        self.StopPromptJourney = channel.unary_unary(
                '/generation_control.GenerationControl/StopPromptJourney',
                request_serializer=generation__control__pb2.GetStateRequest.SerializeToString,
                response_deserializer=generation__control__pb2.ControlResponse.FromString,
                _registered_method=True)


class GenerationControlServicer(object):
    """Generation control service for real-time diffusion parameters
    """

    def SetPrompt(self, request, context):
        """Update the prompt
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGenerationParams(self, request, context):
        """Update generation parameters (seed, steps, guidance_scale, strength)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControlNetParams(self, request, context):
        """Update ControlNet parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLoRAParams(self, request, context):
        """Update LoRA parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPromptTravelParams(self, request, context):
        """Update prompt travel parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAcidParams(self, request, context):
        """Update acid processor parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchCuration(self, request, context):
        """Switch curation index
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentState(self, request, context):
        """Get current state of all parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpdate(self, request, context):
        """Batch update multiple parameter groups at once
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartPromptJourney(self, request, context):
        """Start an autonomous prompt journey (headless mode)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJourneyStatus(self, request, context):
        """Get status of a running prompt journey
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopPromptJourney(self, request, context):
        """Stop a running prompt journey
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GenerationControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPrompt,
                    request_deserializer=generation__control__pb2.PromptRequest.FromString,
                    response_serializer=generation__control__pb2.ControlResponse.SerializeToString,
            ),
            'SetGenerationParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGenerationParams,
                    request_deserializer=generation__control__pb2.GenerationParamsRequest.FromString,
                    response_serializer=generation__control__pb2.ControlResponse.SerializeToString,
            ),
            'SetControlNetParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControlNetParams,
                    request_deserializer=generation__control__pb2.ControlNetParamsRequest.FromString,
                    response_serializer=generation__control__pb2.ControlResponse.SerializeToString,
            ),
            'SetLoRAParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLoRAParams,
                    request_deserializer=generation__control__pb2.LoRAParamsRequest.FromString,
                    response_serializer=generation__control__pb2.ControlResponse.SerializeToString,
            ),
            'SetPromptTravelParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPromptTravelParams,
                    request_deserializer=generation__control__pb2.PromptTravelParamsRequest.FromString,
                    response_serializer=generation__control__pb2.ControlResponse.SerializeToString,
            ),
            'SetAcidParams': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAcidParams,
                    request_deserializer=generation__control__pb2.AcidParamsRequest.FromString,
                    response_serializer=generation__control__pb2.ControlResponse.SerializeToString,
            ),
            'SwitchCuration': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchCuration,
                    request_deserializer=generation__control__pb2.SwitchCurationRequest.FromString,
                    response_serializer=generation__control__pb2.ControlResponse.SerializeToString,
            ),
            'GetCurrentState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentState,
                    request_deserializer=generation__control__pb2.GetStateRequest.FromString,
                    response_serializer=generation__control__pb2.CurrentStateResponse.SerializeToString,
            ),
            'BatchUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpdate,
                    request_deserializer=generation__control__pb2.BatchUpdateRequest.FromString,
                    response_serializer=generation__control__pb2.ControlResponse.SerializeToString,
            ),
            'StartPromptJourney': grpc.unary_unary_rpc_method_handler(
                    servicer.StartPromptJourney,
                    request_deserializer=generation__control__pb2.PromptJourneyRequest.FromString,
                    response_serializer=generation__control__pb2.PromptJourneyResponse.SerializeToString,
            ),
            'GetJourneyStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJourneyStatus,
                    request_deserializer=generation__control__pb2.GetStateRequest.FromString,
                    response_serializer=generation__control__pb2.PromptJourneyStatus.SerializeToString,
            ),
            'StopPromptJourney': grpc.unary_unary_rpc_method_handler(
                    servicer.StopPromptJourney,
                    request_deserializer=generation__control__pb2.GetStateRequest.FromString,
                    response_serializer=generation__control__pb2.ControlResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'generation_control.GenerationControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('generation_control.GenerationControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GenerationControl(object):
    """Generation control service for real-time diffusion parameters
    """

    @staticmethod
    def SetPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/SetPrompt',
            generation__control__pb2.PromptRequest.SerializeToString,
            generation__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGenerationParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/SetGenerationParams',
            generation__control__pb2.GenerationParamsRequest.SerializeToString,
            generation__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetControlNetParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/SetControlNetParams',
            generation__control__pb2.ControlNetParamsRequest.SerializeToString,
            generation__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetLoRAParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/SetLoRAParams',
            generation__control__pb2.LoRAParamsRequest.SerializeToString,
            generation__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPromptTravelParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/SetPromptTravelParams',
            generation__control__pb2.PromptTravelParamsRequest.SerializeToString,
            generation__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetAcidParams(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/SetAcidParams',
            generation__control__pb2.AcidParamsRequest.SerializeToString,
            generation__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchCuration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/SwitchCuration',
            generation__control__pb2.SwitchCurationRequest.SerializeToString,
            generation__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/GetCurrentState',
            generation__control__pb2.GetStateRequest.SerializeToString,
            generation__control__pb2.CurrentStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/BatchUpdate',
            generation__control__pb2.BatchUpdateRequest.SerializeToString,
            generation__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartPromptJourney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/StartPromptJourney',
            generation__control__pb2.PromptJourneyRequest.SerializeToString,
            generation__control__pb2.PromptJourneyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJourneyStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/GetJourneyStatus',
            generation__control__pb2.GetStateRequest.SerializeToString,
            generation__control__pb2.PromptJourneyStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopPromptJourney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/generation_control.GenerationControl/StopPromptJourney',
            generation__control__pb2.GetStateRequest.SerializeToString,
            generation__control__pb2.ControlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
